site_name: GMGI Fisheries Handbook
repo_url: https://github.com/GMGI-Fisheries/resources
edit_uri: blob/master/docs
theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
  icon:
    edit: material/pencil
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: 'index.md'
  - 'Computing Hardware':
    - GMGI: 'Computing_GMGI.md'
    - Northeastern University: 'Computing_NU.md'
  - Data Management: 'Data_Management.md'
  - Data Transfer: 'Data_To_Server.md'
  - 'Computing Resources': 
    - Basics: 'Computing_Begin_Resources.md'
    - R Resources: 'Data Visualization in R.md'
    - Intro to Github: 'tbd.md'
    - Intro to HPC: 'Introduction to HPC.md'
    - Intro to Conda: '.md'
    - Intro to Containers: 'Introduction to Containers.md'
    - Intro to Workflow Managers: 'Introduction to Workflow Managers.md'
  - 'eDNA: 12S metabarcoding':
    - 00-Create-conda-env: '00-creating_eDNA_conda_env.md'
    - 01-ampliseq-12S: 'eDNA 12S metab/01-Metabarcoding ampliseq_12S_Riaz.md'
    - 02-outlier-12S: 'eDNA 12S metab/02-outlier_detection-template-12S.md'
    - 03-tax_assign-12S: 'eDNA 12S metab/03-tax_assignment-template-12S.md'
    - 04-report_generation: 'eDNA 12S metab/04-report_generation-template-12S.md'
    - 05-heatmap: 'eDNA 12S metab/05-heatmap-template-12S.md'
  - 'eDNA: COI metabarcoding':
    - 00-Create-conda-env: '00-creating_eDNA_conda_env.md'
    - 01-ampliseq-COI: 'eDNA COI metab/01-Metabarcoding ampliseq COI.md'
  - 'eDNA: qPCR':
    - 01-dfprep-analysis: 'eDNA qPCR/qPCR-analysis-template.md'
  - 'Population Genomics':
    - coming soon!: 'PopGen/eDNA_01.md'
  - 'Epigenetic Aging':
    - coming soon!: 'EpiAge/eDNA_01.md'
  - 'Genome Assembly':
    - coming soon!: 'tbd.md'

